### ISSUE TITLE
在iOS11以下的系统 右边按钮偏移位置不理想 

### ISSUE THREAD

**Issue by ChivalrousL** [spicyShrimp/UINavigation-SXFixSpace-Swift#1]
在iOS11以下，设置图片的右侧按钮位置是正确的，但是仅设置文字的右侧按钮位置不合理，设置defultFixSpace = 0 的情况下已经超出屏幕范围了。
我将UIBarButtonItemFixSpace.swift文件中第177行的内容作了以下修改，不知道这样修改合不合理
if item.title == nil {
                        rightBarButtonItems = [space, item]
                    } else {
                        rightBarButtonItems = [item, space]
                    }

**Comment by spicyShrimp** [comment]
无需修改177行内容
创建按钮使用下面的方法即可,替换系统原来的方法
navigationItem.rightBarButtonItem = UIBarButtonItem(title: "搜索", target: self, action: #selector(serach))

**Comment by ChivalrousL** [comment]
了解，谢谢
