### ISSUE TITLE
不兼容项目里面有用objective-C的方法

### ISSUE THREAD

**Issue by daishuyi** [spicyShrimp/UINavigation-SXFixSpace-Swift#3]

**Comment by daishuyi** [comment]
我这边项目中使用了
static func image(color:UIColor) -> UIImage{
        let rect = CGRect(x: 0, y: 0, width: 1, height: 1)
        UIGraphicsBeginImageContext(rect.size)
        let context = UIGraphicsGetCurrentContext()
        context!.setFillColor(color.cgColor)
        context!.fill(rect)
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return image!
    }
将颜色转为图片的方法，运行的使用这里的 UIGraphicsBeginImageContext会报错

**Comment by spicyShrimp** [comment]
导航栏设置没有任何使用系统Graphic方法,不会存在Context报错的原因,
UIGraphicsBeginImageContext 或者 UIGraphicsEndImageContext的报错很多都是项目中存在其他的上下文使用上的问题
